tests = [ {'description': 'Level 1-2',
    'steps': [ {'inputs': [('PINA',0x02)], 'iterations': 5 } ],
    'expected': [('PORTC',0x3F)],
    },
    {'description': 'Level 3-4',
    'steps': [ {'inputs': [('PINA', 0x04)],'iterations': 5}],
    'expected': [('PORTC',0x3E)],
    }, 
    {'description': 'Level 5-6',
    'steps': [ {'inputs': [('PINA', 0x05)],'iterations': 5}],
    'expected': [('PORTC',0x3C)],
    },
    {'description': 'Level 7-8-9',
    'steps': [ {'inputs': [('PINA', 0x09)],'iterations': 5}],
    'expected': [('PORTC',0x38)],
    },
    {'description': 'Level 10-11-12',
    'steps': [ {'inputs': [('PINA', 0x0B)],'iterations': 5}],
    'expected': [('PORTC',0x70)],
    },
    {'description': 'Level 13-14-15',
    'steps': [ {'inputs': [('PINA',0x0F)], 'iterations': 5 } ],
    'expected': [('PORTC',0x60)],
    },
    ]
#watch = ['<function>::<static-var>','PORTB']
