tests = [ {'description': 'Initial State => PortC = 0x3F',
    'steps': [ {'inputs': [('PINA',0x0E)], 'iterations': 5 } ],
    'expected': [('PORTC',0x02)],
    },
    {'description': 'change => PortB = 0x15',
    'steps': [ {'inputs': [('PINA',0x0E)], 'iterations': 5 }, 
	],
    'expected': [('PORTB',0x15)],
    },
    {'description': 'change 2 => PortB = 0x2A',
    'steps': [ {'inputs': [('PINA',0x0E)], 'iterations': 5 }, 
              {'inputs': [('PINA',0x0E)], 'iterations': 5 },
	],
    'expected': [('PORTB',0x2A)],
    },
    {'description': 'change 3 => PortB = 0x07',
    'steps': [ {'inputs': [('PINA',0x0E)], 'iterations': 5 }, 
              {'inputs': [('PINA',0x0E)], 'iterations': 5 },
              {'inputs': [('PINA',0x0E)], 'iterations': 5 },
	],
    'expected': [('PORTB',0x07)],
    },
    ]
